version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    volumes:
      - ./:/app:cached
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"

  database:
    image: mysql:8.0
    volumes:
      - ./infra/data02/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "127.0.0.1:3306:3306"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "127.0.0.1:81:80"
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: database

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "127.0.0.1:1080:1080"
